package exceptionhandling.enhancement;

public class NPEEhnacementJava14PCC1 {


    /*
        Initially Java does't print in details data
        Prev : we often see or write code that chain methods in Java. But when this code throws a NullPointerException, it can become difficult to know from where the exception originates.

        Now : Java 14 Onwards we are printing in details data of the exceptions.
              Ie RCA for the same.
              
            *SAP implemented Helpful NullPointerExceptions for their commercial JVM in 2006. 
            It was proposed as an enhancement to the OpenJDK community in February 2019, and quickly after that, 
            it became a JEP.  Consequently, the feature was finished and pushed in October 2019 for the JDK 14 release.

            *In essence, JEP 358 aims to improve the readability of NullPointerExceptions, generated by JVM, by describing which variable is null.

            *JEP 358 brings a detailed NullPointerException message by describing the null variable, alongside the method, filename, and line number. 
            It works by analyzing the program’s bytecode instructions. Therefore, it’s capable of determining precisely which variable or expression was null.

            Most importantly, the detailed exception message is switched off by default in JDK 14. To enable it, we need to use the command-line option:



            Firstly, a detailed message computation is only done when the JVM itself throws a NullPointerException — the computation won’t be performed if we explicitly throw the exception in our Java code. The reason behind this is that, in these situations, most probably we already pass a meaningful message in the exception constructor.

            Secondly, JEP 358 calculates the message lazily, meaning only when we print the exception message and not when the exception occurs. As a result, there shouldn’t be any performance impact for the usual JVM flows, where we catch and rethrow exceptions, since we don’t always print the exception message.

            Finally, the detailed exception message may include local variable names from our source code. Thus, we could consider this a potential security risk. However, this only happens when we run code that was compiled with the -g flag activated, which generates and adds debug information into our class file.
    
    */
    public static void main(String[] args) {
        String str = null;

        System.err.println(str.toLowerCase());
        /*
            OP :
            /usr/bin/env /usr/lib/jvm/java-17-openjdk-amd64/bin/java -XX:+ShowCodeDetailsInExceptionMessages --module-path /home/ai/Documents/ayarn/cp-practice/bin 
            -m Competive_Programming/exceptionhandling.enhancement.NPEEhnacementJava14PCC1 
        Exception in thread "main" java.lang.NullPointerException: Cannot invoke "String.toLowerCase()" because "str" is null
        at Competive_Programming/exceptionhandling.enhancement.NPEEhnacementJava14PCC1.main(NPEEhnacementJava14PCC1.java:28)
        */
    }
    
}
